### ISSUE TITLE
Not dismounted when swimming

### ISSUE THREAD

**Issue by Stressy23** [echoes-emu/echoes-bt#688] opened 2023-01-10 23:11 UTC
Horse goes invisible but you aren't dismounted while swimming 
![image](https://user-images.githubusercontent.com/122374802/211681581-11b2f012-cc47-4dbe-90c1-590f811f5d0e.png)

**Comment by echoes-emu** [comment] 2023-01-11 00:46
Duplicate of #359

**Closed by echoes-emu** 2023-01-11 00:46 UTC
