### ISSUE TITLE
Bog slug slime is yellow ball (Rushock Bog)

### ISSUE THREAD

**Issue by Elraen7** [echoes-emu/echoes-bt#134] opened 2022-02-14 22:21 UTC
You are at: bx89 by119 c0 ox70.5622 oy153.365 oz336.753 r198 (Instance 0)
Whenever a slug does the slime, slime appears as a yellow ball.

![ScreenShot00003](https://user-images.githubusercontent.com/99693447/153956348-5ee99e45-e4e5-4748-baea-db9ce5e8c862.jpg)

**Comment by dawnz85** [comment] 2022-02-15 01:11
duplicate of #66

**Comment by echoes-emu** [comment] 2022-02-16 18:13
Closed the original issue but re-opening this to keep track of the /loc

**Comment by echoes-emu** [comment] 2022-02-16 21:42
Hidden in 73f6f8bb

**Closed by echoes-emu** 2022-02-16 21:42 UTC
Labels: skill, npc, cosmetic
