### ISSUE TITLE
Able to Pick Up Items in Stealth

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#341] opened 2022-04-29 01:20 UTC
Burglar is able to pick up quest items while stealthed without breaking stealth.  Interacting with quest items or chests should break stealth and put the stealth skill on cooldown.

**Comment by echoes-emu** [comment] 2022-09-29 03:48
duplicate of #363

**Closed by echoes-emu** 2022-09-29 03:48 UTC
Labels: bug, skill, player
