### ISSUE TITLE
The Black-Fire - torch bugged

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#807] opened 2023-01-19 13:05 UTC
![image](https://user-images.githubusercontent.com/15167869/213450122-e7cf9eab-6d4d-4421-b15d-cfd2ec4019a6.png)

can't use the torch to burn the black-fire crate

You are at: bx124 by134 c0 ox120.23 oy145.306 oz437.948 r119 (Instance 0)

**Comment by sluwe-vos** [comment] 2023-01-19 13:08
it is just the torch from the black fire on the Northern Hill - the other 2 torches work

**Comment by echoes-emu** [comment] 2023-01-19 14:59
Duplicate of #231

**Closed by echoes-emu** 2023-01-19 14:59 UTC
