### ISSUE TITLE
Dread effect in Man Tutorial doesn't activate at the same point as a video.

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#877] opened 2023-02-10 00:55 UTC
I was comparing a man tutorial video to the game and noticed this discrepancy with the dread effect. In the video, the dread effect seems to start at approximately this location: 

You are at: bx246 by161 c48 ox54.6965 oy-34.513 oz-117.438 r59 (Instance 3)

But you don't receive it until 

You are at: bx246 by161 c48 ox69.2759 oy-35.1591 oz-117.438 r67 (Instance 3)

Here's from the video. https://www.youtube.com/watch?v=8HV2yrZGS0U The dread effect hits at 4:29, it tiers (red on Morale bar) up at 4:32, 4:35, 4:39, 4:42, 4:45, 4:48, 4:51 and 4:54. this screen shot was taken at 4:57 

![image](https://user-images.githubusercontent.com/122328856/217971963-5fdfecbb-c94f-4114-b8f3-81f145f1cc98.png)

This image is from the game at the same 'effect' level:

![image](https://user-images.githubusercontent.com/122328856/217974495-e3189d95-3235-499e-bb13-e801a003134a.png)

As you can see, the effect is similar but doesn't have quite the same look.

The other thing I noticed is that this effect doesn't show up when you get the dread, as can be seen in the video as a flash at 4:29 and again at 4:31 (which seems to correspond with where EoA give the dread)

![image](https://user-images.githubusercontent.com/122328856/217972666-25cc9f35-0ef7-419c-8629-766e194a835c.png)

The other thing I noticed is that Mundo walks into the area after the rider leaves, but he runs in the video

Selection: 0x031F6A1003000074 (0x041F6A1000000054)
 DID: 0x700000CD
 Loc: bx246 by161 c16 ox71.945 oy-49.171 oz-117.387 r118 (Instance 3)
 Move table: 0x070000B1
State stack:
(Patrol) PatrolExit @ 0.5x
(Drama) Scriptlink_Custom2
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
Drama: Scriptlink_Custom2

**Comment by bcp19** [comment] 2023-02-10 01:09
I did check out other areas known to have dread, like the Giant Champion in Misty Mountains, the dread effect is instant there are well, but only is a 6, which doesn't have the same blurring effect that 8 does.

**Comment by echoes-emu** [comment] 2023-02-10 17:30
Duplicate of #385

**Closed by echoes-emu** 2023-02-10 17:30 UTC

**Comment by bcp19** [comment] 2023-02-10 19:08
There's more to this than just the dread... Location of effect and speed of character...
