### ISSUE TITLE
Bog lurker enemies spawn a root as an ally for me that attacks my allies

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#393] opened 2022-05-07 23:40 UTC
You are at: bx169 by112 c0 ox5.30479 oy135.713 oz335.835 r6 (Instance 0)

**Comment by echoes-emu** [comment] 2022-05-08 14:04
Duplicate of #360

**Closed by echoes-emu** 2022-05-08 14:04 UTC
Labels: bug
