### ISSUE TITLE
invisible wall does not seem to be in the right place

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#528] opened 2022-07-25 16:31 UTC
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx114 by128 c0 ox158.575 oy84.9932 oz386.029 r0 (Instance 0)

**Comment by dawnz85** [comment] 2022-07-25 20:15
Crash on teleporting to this location. Landscape looks fine so perhaps caused by the quest interior below.

**Comment by echoes-emu** [comment] 2022-07-31 22:27
Will be fixed in the next release

**Closed by echoes-emu** 2022-07-31 22:27 UTC
Labels: bug, content
