### ISSUE TITLE
Aoe heals heal people in the part at different times for some reason

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#452] opened 2022-05-12 22:00 UTC

**Comment by MasterTeal** [comment] 2022-05-12 22:02
I have noticed this same issue with champion skill "Sound the Attack" applying the stun to different targets at slightly different times. Not sure if it is related.

**Comment by echoes-emu** [comment] 2022-05-13 01:20
Duplicate of #243

**Closed by echoes-emu** 2022-05-13 01:20 UTC
