### ISSUE TITLE
Map Home bugged

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#272] opened 2022-03-23 00:34 UTC
![image](https://user-images.githubusercontent.com/99280428/159598990-b446f183-695b-419b-98d3-392cd3f34db3.png)

Map home will not decrease in cd. it stays at 7 mins. The name of the character is "Ilikemen"

**Comment by echoes-emu** [comment] 2022-03-23 01:30
Duplicate of #263

**Closed by echoes-emu** 2022-03-23 01:30 UTC
