### ISSUE TITLE
Sometimes when zoning into Forsaken Inn you get a black screen

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#634] opened 2022-12-28 01:34 UTC
location of forsaken inn black screen bug You are at: bx132 by112 c4 ox104.208 oy138.074 oz400.039 r13

**Comment by dawnz85** [comment] 2022-12-28 08:37
This position has an interior cell but is on landscape. Likely dupe of #640

**Closed by dawnz85** 2022-12-28 08:37 UTC
