### ISSUE TITLE
This item has a durability problem and repair cost problem

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#537] opened 2022-08-01 12:42 UTC
![image](https://user-images.githubusercontent.com/99280428/182150217-9a705c5f-e8a9-4e85-81dd-2c44dc37586e.png)

**Comment by echoes-emu** [comment] 2022-08-02 12:12
Duplicate of #446

**Closed by echoes-emu** 2022-08-02 12:12 UTC
