### ISSUE TITLE
Places of the Dwarves deed did not start

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#685] opened 2023-01-10 20:58 UTC
When I got to Thorin's Gate, Frerrin's Court did not trigger the Places of the Dwarves deed. I did not receive notification of it starting until I was actually at Thorin's Gate at the top of the stairs and Frerrin's Court was still grey

**Comment by bcp19** [comment] 2023-01-10 21:11
Neither Frerrin's Court nor Silverdeep Mine ere added to the deed when I visted both locations

**Comment by bcp19** [comment] 2023-01-11 04:03
Update: When I created a dwarf character, the deed works normally

**Comment by bcp19** [comment] 2023-01-11 04:15
Correction, Dwarf got Frerrin's court, but did not get Silver Deep Mine. I had skipped the Intro on Dwarf, so it's almost as if the old bug where it started the deeds in the intro is marking the Silver Deep where you start at but since I didn't run past Frerrin's it allowed me to get it.

**Comment by bcp19** [comment] 2023-01-11 04:30
Confirmed. Deleted Elf character, skipped intro and can get Frerrins and Silver Deep for the deed. Down side, deleted and recreated character no longer has +

**Comment by MasterTeal** [comment] 2023-01-11 16:38
Same issue with race of man character and Browne's Folly near Archet.

Linking possible related issues #534 and #674

**Comment by merloechoed** [comment] 2023-01-13 03:35
Looks like it's still happening.
For both regional quest meta deed and the explorer deed.
Regional quests meta deed is starting during the intro (not sure if WAI).
Also visited places that count towards an explorer deed and after the intro, when the explorer deed really unlocks, those visited places during the intro won't count towards the explorer deed.

Possible fix is to prevent, at least the explorer deeds, from advancing during the intro instances.

**Comment by MasterTeal** [comment] 2023-01-13 05:53
I suspect that the fix is not to tie to a level but rather to tie ability to start deeds to the player getting "Novice" which you get from turning in the final quest of the intro once you are in the overworld

**Comment by merloechoed** [comment] 2023-01-13 17:06
> I suspect that the fix is not to tie to a level but rather to tie ability to start deeds to the player getting "Novice" which you get from turning in the final quest of the intro once you are in the overworld

Indeed. I suspect that was the solution they used on live game, requiring the "Novice" passive skill to advance at least the regional quests meta deeds and explorer deeds.

In live game the "Veteran" passive skill can be bought in store, and that makes you skip the intro instance, if I'm not mistaken.
Not sure if that is present in some form in EoA, but if it is, might need to check for "Novice" or "Veteran" passive skill present, as one might replace the other. But this is only necessary in the case if "Veteran" passive skill can be obtained in EoA, if not, just checking for "Novice" passive skill before bestowing/advancing said deeds might be enough indeed.

**Comment by echoes-emu** [comment] 2023-01-18 13:58
Duplicate of #711

**Closed by echoes-emu** 2023-01-18 13:58 UTC
Labels: bug, deed
