### ISSUE TITLE
Role Playing Color Change on Name

### ISSUE THREAD

**Issue by Grimbatul** [echoes-emu/echoes-bt#680] opened 2023-01-10 18:17 UTC
Normally when we type ./rp on  character name normally goes white. Once in a kinship it becomes shiny blue. Unfortunately it has no effect at all at the moment.

For your information.

**Comment by echoes-emu** [comment] 2023-01-10 18:32
Duplicate of #605

**Closed by echoes-emu** 2023-01-10 18:32 UTC
