### ISSUE TITLE
Error in displaying the time in a letter about an auction sale

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#728] opened 2023-01-12 19:14 UTC
Время отображается некорректно в письме с аукциона.

![image](https://user-images.githubusercontent.com/122410042/212159615-1467cadc-3986-43ff-8c33-1079c63cc051.png)

**Comment by echoes-emu** [comment] 2023-01-12 19:24
duplicate of #661, please use English in your reports!

**Closed by echoes-emu** 2023-01-12 19:24 UTC

**Comment by rabekon** [comment] 2023-01-12 19:46
> duplicate of #661, please use English in your reports!

Oops, I got confused in two languages and was sure I was writing in English)) sorry.
