### ISSUE TITLE
Seems like mobs respawn too fast in Agamaur elite areas

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#308] opened 2022-04-04 20:46 UTC
In this place especially, mobs respawn very fast:
bx150 by120 c0 ox89.4533 oy83.0959 oz338.521 r57

**Comment by echoes-emu** [comment] 2022-04-04 22:20
Looks like a duplicate of #207

**Closed by echoes-emu** 2022-04-04 22:20 UTC
Labels: investigate
