### ISSUE TITLE
LM - Quest: Friend of Hares

### ISSUE THREAD

**Issue by merloechoed** [echoes-emu/echoes-bt#793] opened 2023-01-17 02:10 UTC
Looks like the hare's den isn't spawning anywhere to be seen around the area the quest description says "den lies due west of the Outer Gates of Garth Agarwen, northeast of Ost Guruth".

If I remember well, it's a 3 quests chain (hare, sparrow and turtle), might be worth to investigate the spawn for the dens in the following quests too.

Quest: Friend of Hares
Quest Giver: Radagast the Brown

You are at: bx149 by118 c2 ox-16.1274 oy-8.8583 oz-219.724 r73 (Instance 0)

Selection: 0x0319576000000380 (0x0419576000000048)
 DID: 0x7000067B
 Loc: bx149 by118 c2 ox-12.941 oy-9.50147 oz-219.134 r199 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by bcp19** [comment] 2023-01-17 02:25
The hare's den is down in the southern swamp, the quest text is off.

**Comment by merloechoed** [comment] 2023-01-17 02:39
I've been running around that location using the key mapping "Select Nearest Item" with no luck finding any object related to a den so far. Did you do this quest recently and found the hare's den?

**Comment by merloechoed** [comment] 2023-01-17 02:51
For anyone wanting to do further investigation, the location mentioned by @bcp19 is:

You are at: bx148 by110 c0 ox158.722 oy115 oz341.991 r9 (Instance 0)

**Comment by bcp19** [comment] 2023-01-17 03:06
I have not done the quest, I never played a loremaster back in the day

**Comment by bcp19** [comment] 2023-01-17 05:29
Ok, after a careful search, I found the location, the quest test is correct, Due west of the OUTER GATES... Go to the Enterance to the instance and head west... 

You are at: bx150 by120 c0 ox3.23303 oy133.144 oz335.298 r130 (Instance 0)

**Comment by bcp19** [comment] 2023-01-17 05:36
Brought the hare back to the tower, but the hare doesn't phase into the tower, so the quest fails because you cannot get him back within the 5 min time limit

**Comment by merloechoed** [comment] 2023-01-17 06:34
> Brought the hare back to the tower, but the hare doesn't phase into the tower, so the quest fails because you cannot get him back within the 5 min time limit

Same issue happened.

**Comment by merloechoed** [comment] 2023-01-19 03:51
At first, it might look like it's the issue of "Pets despawn on location change", but when we leave the tower again, the hare is still outside, so it's more like a problem of "Escorts don't follow the player in teleports".

**Comment by echoes-emu** [comment] 2023-03-08 00:12
Duplicate of #928

**Closed by echoes-emu** 2023-03-08 00:12 UTC
Labels: quest, investigate
