### ISSUE TITLE
[Quest] Old Sally - Old Sally Vitals Not Visible

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#414] opened 2022-05-09 14:38 UTC
Cannot see vitals of escort NPC Old Sally during escort quest.

Quest Giver Belco Brockhouse loc: bx94 by114 c0 ox129.473 oy77.4876 oz416.359 r253 (Instance 0)
Old Sally loc: bx95 by113 c0 ox157.999 oy1.78139 oz412.18 r146 (Instance 0)

**Comment by dawnz85** [comment] 2022-05-09 15:02
See also #401

**Comment by echoes-emu** [comment] 2022-05-09 15:51
Duplicate of #401

**Closed by echoes-emu** 2022-05-09 15:51 UTC
