### ISSUE TITLE
Enemy NPCs receive campfire buff

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#227] opened 2022-03-11 20:00 UTC
campfire buff on enemy

![image](https://user-images.githubusercontent.com/99280428/157950424-d17424ee-bdfb-41f6-81a5-1fcd5b4594a6.png)

**Comment by dawnz85** [comment] 2022-03-11 21:24
Duplicate of #212

**Closed** 2022-03-11 21:24 UTC
