### ISSUE TITLE
Instance: Unravelling the Thread - Drama plays for each member of the fellowship 

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#498] opened 2022-06-09 06:26 UTC
This results in NPCs doing the same thing multiple times depending on the amount of members in fellowship.

**Comment by dawnz85** [comment] 2022-06-10 03:31
Possible dupe of #318

**Comment by echoes-emu** [comment] 2022-09-28 20:33
This should be fixed now

**Closed by echoes-emu** 2022-09-28 20:34 UTC
Labels: bug, scripting
