### ISSUE TITLE
Stuck after fast-travel between Thorin's Hall and West Bree

### ISSUE THREAD

**Issue by Gingerbreadfriend** [echoes-emu/echoes-bt#556] opened 2022-09-20 12:05 UTC
Character will be frozen in place upon arrival even after dismounting, re-logging is needed to fix. 

Interestingly you can fast travel from Michel Delving to West Bree with no issues, but you will get stuck if you fast travel from Michel Delving to Thorin's Hall. Michel Delving can be fast travelled to from both locations without issue.

**Comment by echoes-emu** [comment] 2022-10-20 02:46
Cannot reproduce, re-open if it pops up again

**Comment by Gingerbreadfriend** [comment] 2022-10-24 22:28
Issue still persists, tried on two separate characters and each got stuck on arrival at Thorin's Hall from Bree.

**Comment by echoes-emu** [comment] 2022-10-25 18:05
Fixed in dd54e491

**Closed by echoes-emu** 2022-10-25 18:05 UTC
Labels: bug
