### ISSUE TITLE
Possible to acquire quests that are intended for higher levels

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#278] opened 2022-03-23 07:51 UTC
If the quest is part of a chain where the pre-req is of an acceptable level, and you complete it, the subsequent quest is offered
even if its above your level.
![image](https://user-images.githubusercontent.com/96521062/159649477-116167d1-0694-4a10-9b99-632b8cc90185.png)
If I didn't hit accept, I would not have been able to pick it up afterwards

**Comment by echoes-emu** [comment] 2022-03-23 13:15
Duplicate of #146

**Closed by echoes-emu** 2022-03-23 13:15 UTC
Labels: bug, player
