### ISSUE TITLE
Ranged auto-attacks should automatically disable when tabbing to a different target.

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#657] opened 2022-12-29 03:00 UTC

**Comment by bcp19** [comment] 2023-01-10 03:01
TBH, this is not a bug. If your auto attack is on and you tab target to a new mob, your auto attack will continue. The only time your auto attack should end is when everything aggro'd on you dies

**Comment by echoes-emu** [comment] 2023-01-12 00:58
Closing as per comment above

**Closed by echoes-emu** 2023-01-12 00:58 UTC
Labels: bug, skill, investigate
