### ISSUE TITLE
Multiple duplication of an item in a prologue instance.

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#687] opened 2023-01-10 23:09 UTC
Instance:  The refuge of  Edhelion

An item (class weapon) can be taken from a corpse an infinite number of times. The item costs 1 copper. You can get rich. Hooray.

You are at: bx57 by137 c0 ox100.661 oy158.195 oz689.862 r121 (Instance 3)

![ScreenShot00144](https://user-images.githubusercontent.com/122410042/211681334-dafb77e6-145c-470d-baa4-ec28316217b2.jpg)

**Comment by echoes-emu** [comment] 2023-01-11 00:46
Duplicate of #544

**Closed by echoes-emu** 2023-01-11 00:46 UTC
